# Generated by Django 2.1.8 on 2020-04-16 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=128, verbose_name='用户名')),
                ('user_pwd', models.CharField(max_length=128, verbose_name='用户密码')),
                ('user_telphone', models.CharField(max_length=128, verbose_name='用户手机号')),
                ('reserve1', models.CharField(max_length=128, verbose_name='保留字段1')),
                ('reserve2', models.CharField(max_length=128, verbose_name='保留字段2')),
                ('reserve3', models.CharField(max_length=128, verbose_name='保留字段3')),
                ('reserve4', models.CharField(max_length=128, verbose_name='保留字段4')),
            ],
            options={
                'verbose_name_plural': '用户表',
                'db_table': 'User',
            },
        ),
    ]
