# Generated by Django 2.1.8 on 2020-04-19 11:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Search_Key',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_key', models.CharField(max_length=128, verbose_name='用户搜索关键词')),
                ('search_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='搜索时间')),
                ('reserve1', models.CharField(max_length=128, verbose_name='保留字段1')),
                ('reserve2', models.CharField(max_length=128, verbose_name='保留字段2')),
                ('reserve3', models.CharField(max_length=128, verbose_name='保留字段3')),
                ('reserve4', models.CharField(max_length=128, verbose_name='保留字段4')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='search.User')),
            ],
            options={
                'verbose_name_plural': '用户搜索关键词表',
                'db_table': 'User_Search_Key',
            },
        ),
    ]
